FROM kolla/centos-source-nova-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="nova-novncproxy" build-date="20180904"







        



RUN yum -y install novnc && yum clean all && rm -rf /var/cache/yum




USER nova