FROM kolla/centos-source-redis-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="redis" build-date="20180904"






    

RUN yum -y install redis && yum clean all && rm -rf /var/cache/yum




USER redis