FROM kolla/centos-source-ceilometer-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="ceilometer-ipmi" build-date="20180904"






    
        
    



RUN yum -y install ipmitool && yum clean all && rm -rf /var/cache/yum




USER ceilometer