FROM kolla/centos-source-skydive-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="skydive-agent" build-date="20180904"







    

RUN yum -y install openvswitch && yum clean all && rm -rf /var/cache/yum



