FROM kolla/centos-source-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="dnsmasq" build-date="20180904"






RUN yum -y install dnsmasq && yum clean all && rm -rf /var/cache/yum


