FROM kolla/centos-source-ovn-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="ovn-controller" build-date="20180904"






    


RUN yum -y install openvswitch-ovn-host && yum clean all && rm -rf /var/cache/yum


