FROM kolla/centos-source-manila-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="manila-data" build-date="20180904"






    

        

     



RUN yum -y install nfs-utils && yum clean all && rm -rf /var/cache/yum




USER manila