FROM kolla/centos-source-neutron-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="neutron-l3-agent" build-date="20180904"






   
       
   

RUN yum -y install libreswan radvd dibbler-client && yum clean all && rm -rf /var/cache/yum






USER neutron