FROM kolla/centos-source-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="cron" build-date="20180904"






    


RUN yum -y install cronie logrotate && yum clean all && rm -rf /var/cache/yum


