FROM kolla/centos-source-sahara-base:7.0.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="sahara-engine" build-date="20180904"






    
       
    


RUN yum -y install nc && yum clean all && rm -rf /var/cache/yum




USER sahara